### PR TITLE
Fixes bower dependency merging with package.json

### LINKED ISSUE #51: The dependencies in bower.json get overwritten by package.json dependencies
When executing `compile` in a project where you have a bower file, the `dependencies` and the `devDevpendencies` get overwritten by the ones specified in package.json

### PR DESCRIPTION
**Pull request by pflannery**
Adds license, keywords and description to bower merge process
Adds bower.json to tests
Fixes tab issues in README between ./src and ./out-expected

fixes #51

### CODE REVIEW

**Comment by balupton** [comment]
What's your npm handle? I'll add you as a maintainer and publisher

**Comment by pflannery** [comment]
ok thanks. It's pflannery

**Comment by balupton** [comment]
Done!

**Comment by pflannery** [comment]
LGTM

**Pull request merged**
