### PR TITLE
stops merging enhanced package dependencies

### PR DESCRIPTION
**Pull request by pflannery**

### CODE REVIEW

**Comment by pflannery** [comment]
This was causing me a problem where bower dependencies were over writing npm dependencies.

@balupton PTAL

**Comment by balupton** [comment]
I will do a guide this week. This PR and the change in v0.4.0 shouldn't be necessary if the `projectz.cson` file is configured correctly.

**Comment by pflannery** [comment]
ok. I must admit I've not been using the projectz cson which probably explains why I'm seeing this merge issue.
Maybe it's something we should disable when no cson config is present?

**Comment by pflannery** [comment]
I've now discovered that having a projectz.cson doesn't fix this, but putting a ```"dependencies": {}``` in package.json stops it from copying them from bower.json to package.json. 

I look forward to your guide!. thanks.

**Comment by balupton** [comment]
Let's keep the PR open for now, until I can prove we can fix this.

**Comment by balupton** [comment]
v1.0.0 may fix this - happy to re-open if not

**Pull request closed without merging**
