### PR TITLE
feat(cli): shows up help if no arguments were supplied

### LINKED ISSUE #93: (cli): Nothing shows up if no arguments were provided
Nothing seems to happen if `projectz` was supplied without any sort of arguments.

### PR DESCRIPTION
**Pull request by jamesgeorge007**
Fixes #93

### CODE REVIEW

**Comment by jamesgeorge007** [comment]
cc @balupton

**Comment by balupton** [comment]
Great thanks. I've added you to the bevry team with write access to this repo. To do a release follow the contributing.md guide and add the changelog entry then run the release command as indicated in the contributing guide. Continuous integration will do the rest.

**Comment by balupton** [comment]
Actually seems that there is some base file issue happening. This would be fixed by me running github.com/bevry/boundation on it, however my computer is in repair so I cannot do it without my phone. Give me a month for my computer to get back, and we can see if we can sort it out. Perhaps grab a time after august 7th on balupton.com/meet or ping me at bevry.me/discord in august and that will remind me.

**Comment by jamesgeorge007** [comment]
It may take some time in order to familiarise with the code-base. Also, I have my project under active development [Mevn-CLI](http://github.com/madlabsinc/mevn-cli).

**Comment by balupton** [comment]
released to v1.7.5

**Pull request merged**
